//go:build linux

package main

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"sync"
	"syscall"
	"time"

	"connectrpc.com/connect"
	v1 "github.com/hancomac/circulusd/api/generated/circulus/v1alpha"
	v1connect "github.com/hancomac/circulusd/api/generated/circulus/v1alpha/circulusv1alphaconnect"
	"golang.org/x/sys/unix"
	"google.golang.org/protobuf/proto"
)

// sandboxClient talks to sandboxd over its private Unix socket with the
// connect-go clients generated by circulusd. It follows the client rules of
// internal/sandboxrpc/client_linux.go: the peer must be the expected uid, the
// one-time nonce is spent on a single handshake, and every response is
// validated against the request id and descriptor digest.
type sandboxClient struct {
	socketPath string
	serverUID  uint32
	sandboxID  []byte
	generation uint64

	control v1connect.ControlServiceClient
	process v1connect.SandboxProcessServiceClient

	mu        sync.Mutex
	nonce     []byte
	session   string
	attempted bool
	failure   error
}

func newSandboxClient(socketPath string, serverUID uint32, sandboxID string, generation uint64, nonce []byte) *sandboxClient {
	client := &sandboxClient{
		socketPath: socketPath,
		serverUID:  serverUID,
		sandboxID:  []byte(sandboxID),
		generation: generation,
		nonce:      append([]byte(nil), nonce...),
	}
	transport := &http.Transport{
		DisableCompression: true,
		// sandboxd closes idle connections after 30 s; a fresh connection per
		// request avoids racing that with a reused one.
		DisableKeepAlives: true,
		DialContext:       client.dial,
	}
	httpClient := &http.Client{Transport: transport}
	options := []connect.ClientOption{connect.WithReadMaxBytes(maximumMessageBytes), connect.WithSendMaxBytes(maximumMessageBytes)}
	client.control = v1connect.NewControlServiceClient(httpClient, "http://sandbox.invalid", options...)
	client.process = v1connect.NewSandboxProcessServiceClient(httpClient, "http://sandbox.invalid", options...)
	return client
}

func (client *sandboxClient) dial(ctx context.Context, _, _ string) (net.Conn, error) {
	connection, err := (&net.Dialer{}).DialContext(ctx, "unix", client.socketPath)
	if err != nil {
		return nil, err
	}
	uid, err := peerUID(connection)
	if err != nil {
		_ = connection.Close()
		return nil, err
	}
	if uid != client.serverUID {
		_ = connection.Close()
		return nil, fmt.Errorf("sandboxd socket peer uid %d, expected %d", uid, client.serverUID)
	}
	return connection, nil
}

func peerUID(connection net.Conn) (uint32, error) {
	syscallConnection, ok := connection.(syscall.Conn)
	if !ok {
		return 0, errors.New("connection has no syscall handle")
	}
	raw, err := syscallConnection.SyscallConn()
	if err != nil {
		return 0, err
	}
	var credential *unix.Ucred
	var optionError error
	if err := raw.Control(func(fd uintptr) {
		credential, optionError = unix.GetsockoptUcred(int(fd), unix.SOL_SOCKET, unix.SO_PEERCRED)
	}); err != nil {
		return 0, err
	}
	if optionError != nil || credential == nil {
		return 0, errors.New("peer credential is unavailable")
	}
	return credential.Uid, nil
}

// handshake spends the launch nonce; it is attempted exactly once.
func (client *sandboxClient) handshake(ctx context.Context) error {
	client.mu.Lock()
	defer client.mu.Unlock()
	if client.session != "" {
		return nil
	}
	if client.attempted {
		if client.failure != nil {
			return client.failure
		}
		return errors.New("one-time handshake is unavailable")
	}
	client.attempted = true
	nonce := client.nonce
	client.nonce = nil
	request := connect.NewRequest(&v1.HandshakeRequest{
		Peer:              v1.ProtocolPeer_PROTOCOL_PEER_EXECUTORD,
		MinimumVersion:    protocolVersion(),
		MaximumVersion:    protocolVersion(),
		FeatureBitmap:     0,
		MaximumFrameSize:  maximumMessageBytes,
		DescriptorDigest:  descriptorDigest(),
		OneTimeNonce:      nonce,
		SandboxId:         &v1.OpaqueId{Value: append([]byte(nil), client.sandboxID...)},
		SandboxGeneration: client.generation,
	})
	response, err := client.control.Handshake(ctx, request)
	if err != nil {
		client.failure = fmt.Errorf("handshake: %w", err)
		return client.failure
	}
	message := response.Msg
	expectedProof := nonceProof(nonce, client.sandboxID, client.generation, v1.ProtocolPeer_PROTOCOL_PEER_SANDBOXD)
	for index := range nonce {
		nonce[index] = 0
	}
	if message == nil || hasUnknownFields(message) || !isProtocolVersion(message.GetSelectedVersion()) ||
		message.GetFeatureBitmap() != 0 || message.GetServerPeer() != v1.ProtocolPeer_PROTOCOL_PEER_SANDBOXD ||
		message.GetMaximumFrameSize() != maximumMessageBytes || !isDescriptorDigest(message.GetDescriptorDigest()) ||
		message.GetStatus().GetName() != "sandbox.process" ||
		message.GetStatus().GetAvailability() != v1.CapabilityAvailability_CAPABILITY_AVAILABILITY_AVAILABLE ||
		!equalBytes(message.GetNonceProof(), expectedProof) {
		client.failure = errors.New("handshake response failed protocol validation")
		return client.failure
	}
	session := response.Header().Get(sessionHeader)
	if session == "" || len(session) > 128 {
		client.failure = errors.New("handshake session is missing")
		return client.failure
	}
	client.session = session
	return nil
}

func (client *sandboxClient) sessionToken() (string, error) {
	client.mu.Lock()
	defer client.mu.Unlock()
	if client.session == "" {
		return "", errors.New("sandbox session is not established")
	}
	return client.session, nil
}

// boundedRPC gives a unary call a client-side deadline matching the wire
// deadline prepareRequest stamps on it, so a wedged sandboxd cannot hold the
// caller (and the session lock) past the protocol's own limit.
func boundedRPC(ctx context.Context) (context.Context, context.CancelFunc) {
	if _, ok := ctx.Deadline(); ok {
		return context.WithCancel(ctx)
	}
	return context.WithTimeout(ctx, defaultRequestTimeout+5*time.Second)
}

func (client *sandboxClient) spawn(ctx context.Context, message *v1.SpawnProcessRequest) (*v1.ProcessHandle, error) {
	session, err := client.sessionToken()
	if err != nil {
		return nil, err
	}
	ctx, cancel := boundedRPC(ctx)
	defer cancel()
	prepared, requestID, err := prepareRequest(ctx, message, newIdempotencyKey())
	if err != nil {
		return nil, err
	}
	request := connect.NewRequest(prepared.(*v1.SpawnProcessRequest))
	request.Header().Set(sessionHeader, session)
	response, err := client.process.Spawn(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("spawn: %w", err)
	}
	handle := response.Msg.GetProcess()
	if validateResponse(response.Msg, response.Msg.GetMeta(), requestID) != nil || handle == nil ||
		!equalBytes(handle.GetSandboxId().GetValue(), client.sandboxID) || handle.GetGeneration() != client.generation ||
		!proto.Equal(handle.GetInvocationId(), message.GetInvocationId()) ||
		len(handle.GetProcessId().GetValue()) == 0 || len(handle.GetProcessId().GetValue()) > 64 {
		return nil, errors.New("spawn response failed protocol validation")
	}
	return proto.Clone(handle).(*v1.ProcessHandle), nil
}

func (client *sandboxClient) writeStdin(ctx context.Context, handle *v1.ProcessHandle, sequence uint64, data []byte) error {
	session, err := client.sessionToken()
	if err != nil {
		return err
	}
	ctx, cancel := boundedRPC(ctx)
	defer cancel()
	message := &v1.WriteStdinRequest{Meta: &v1.RpcRequestMeta{}, Process: handle, ChunkSequence: sequence, Data: data}
	prepared, requestID, err := prepareRequest(ctx, message, newIdempotencyKey())
	if err != nil {
		return err
	}
	request := connect.NewRequest(prepared.(*v1.WriteStdinRequest))
	request.Header().Set(sessionHeader, session)
	response, err := client.process.WriteStdin(ctx, request)
	if err != nil {
		return fmt.Errorf("write stdin: %w", err)
	}
	if validateResponse(response.Msg, response.Msg.GetMeta(), requestID) != nil ||
		response.Msg.GetAcceptedSequence() != sequence || response.Msg.GetAcceptedBytes() != uint64(len(data)) {
		return errors.New("stdin response failed protocol validation")
	}
	return nil
}

func (client *sandboxClient) closeStdin(ctx context.Context, handle *v1.ProcessHandle) error {
	session, err := client.sessionToken()
	if err != nil {
		return err
	}
	ctx, cancel := boundedRPC(ctx)
	defer cancel()
	message := &v1.CloseStdinRequest{Meta: &v1.RpcRequestMeta{}, Process: handle}
	prepared, requestID, err := prepareRequest(ctx, message, newIdempotencyKey())
	if err != nil {
		return err
	}
	request := connect.NewRequest(prepared.(*v1.CloseStdinRequest))
	request.Header().Set(sessionHeader, session)
	response, err := client.process.CloseStdin(ctx, request)
	if err != nil {
		return fmt.Errorf("close stdin: %w", err)
	}
	if validateResponse(response.Msg, response.Msg.GetMeta(), requestID) != nil || !response.Msg.GetClosed() {
		return errors.New("close-stdin response failed protocol validation")
	}
	return nil
}

func (client *sandboxClient) cancel(ctx context.Context, handle *v1.ProcessHandle, reason string) error {
	session, err := client.sessionToken()
	if err != nil {
		return err
	}
	message := &v1.CancelProcessRequest{Meta: &v1.RpcRequestMeta{}, Process: handle, Reason: reason}
	prepared, _, err := prepareRequest(ctx, message, newIdempotencyKey())
	if err != nil {
		return err
	}
	request := connect.NewRequest(prepared.(*v1.CancelProcessRequest))
	request.Header().Set(sessionHeader, session)
	_, err = client.process.Cancel(ctx, request)
	return err
}

// attach opens the ordered event stream after the given sequence. The
// context deadline bounds one attachment; callers re-attach for long runs.
func (client *sandboxClient) attach(ctx context.Context, handle *v1.ProcessHandle, after uint64) (*connect.ServerStreamForClient[v1.ProcessEvent], error) {
	session, err := client.sessionToken()
	if err != nil {
		return nil, err
	}
	message := &v1.AttachProcessRequest{Meta: &v1.RpcRequestMeta{}, Process: handle, AfterSequence: after}
	prepared, _, err := prepareRequest(ctx, message, newIdempotencyKey())
	if err != nil {
		return nil, err
	}
	request := connect.NewRequest(prepared.(*v1.AttachProcessRequest))
	request.Header().Set(sessionHeader, session)
	stream, err := client.process.Attach(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("attach: %w", err)
	}
	return stream, nil
}

// attachDeadline bounds one Attach RPC: the process deadline plus slack,
// capped by the protocol maximum.
func attachDeadline(remaining time.Duration) time.Duration {
	deadline := remaining + 10*time.Second
	if deadline < time.Second {
		deadline = time.Second
	}
	if deadline > maximumRPCDeadline {
		deadline = maximumRPCDeadline
	}
	return deadline
}
